name: qalculate-qt
adopt-info: qalculate-qt
title: Qalculate! (Qt)
version: '5.9.0'
license: GPL-2.0+
summary: The ultimate desktop calculator
description: |
  Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple
  to use but provides power and versatility normally reserved for complicated
  math packages, as well as useful tools for everyday needs (such as currency
  conversion and percent calculation). Features include a large library of
  customizable functions, unit calculations and conversion, physical constants,
  symbolic calculations (including integrals and equations), arbitrary precision,
  uncertainty propagation, interval arithmetic, plotting, and a user-friendly
  interface.

confinement: strict
grade: stable
base: core24
compression: lzo

platforms:
  amd64:
  arm64:

apps:
  qalculate-qt:
    extensions:
      - kde-neon-6
    command: usr/bin/qalculate-qt
    environment:
        GNUPLOT_DRIVER_DIR: "$SNAP/usr/libexec/gnuplot/6.0"
    plugs:
      - home
      - browser-support
  qalc:
    extensions:
      - kde-neon-6
    command: usr/bin/qalc
    environment:
        GNUPLOT_DRIVER_DIR: "$SNAP/usr/libexec/gnuplot/6.0"
  gnuplot:
    extensions:
      - kde-neon-6
    command: usr/bin/gnuplot
    environment:
        GNUPLOT_DRIVER_DIR: "$SNAP/usr/libexec/gnuplot/6.0"

parts:
  libqalculate:
    source: https://github.com/Qalculate/libqalculate.git
    source-tag: v5.9.0
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
    build-environment:
      - CXXFLAGS: -O2 -fsigned-char
    build-packages:
      - libncurses5-dev
      - libreadline-dev
      - libcurl4-gnutls-dev
      - libicu-dev
      - libxml2-dev
      - libgmp-dev
      - libmpfr-dev
      - doxygen
      - pkg-config
    stage-packages:
      - libmpfr6
      - libgmp10
    override-build: |
      patch -p1 < $CRAFT_STAGE/patches/snap-path.patch
      ./autogen.sh
      craftctl default
      echo Stripping qalc
      strip $CRAFT_PART_INSTALL/usr/bin/qalc
    after:
      - patches
    prime:
      - -include
      - -lib/pkgconfig
      - -lib/*.a
      - -share/doc
      - -usr/share/doc
      - -usr/share/lintian

  qalculate-qt:
    source: https://github.com/Qalculate/qalculate-qt/releases/download/v5.9.0/qalculate-qt-5.9.0b.tar.gz
    source-checksum: sha512/8db4f1bf6e2b03af618420e715f133823854e391f5d74531f9609c80d0bd4bf7a3e22382aaa31257004565f29adbe5ad1abea60512fa5ca6898a84dfcea5ddbc
    plugin: qmake
    qmake-parameters:
      - COMPILE_RESOURCES=yes
      - PREFIX=/usr
    build-environment:
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:/snap/kf6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/pkgconfig:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
      - PATH: /snap/kde-qt6-core24-sdk/current/usr/bin/qt6:$PATH
    build-snaps:
      - core24
      - kf6-core24
    build-packages:
      - libgmp-dev
      - libxml2-dev
    after:
      - libqalculate
      - patches
    prime:
      - -share/applications
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/snap/patches/snap.patch

  gnuplot:
    source: https://downloads.sourceforge.net/gnuplot/gnuplot-6.0.4.tar.gz
    source-checksum: sha256/458d94769625e73d5f6232500f49cbadcb2b183380d43d2266a0f9701aeb9c5b
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --without-gd
      - --without-libcerf
      - --without-lua
      - --with-readline=gnu
      - --without-qt
      - --enable-wxwidgets
    after:
      - wxwidgets-sdk
    prime:
      - -share/applications
      - -share/doc
      - -share/man
    override-build: |
      craftctl default
      echo Stripping gnuplot
      strip $CRAFT_PART_INSTALL/usr/bin/gnuplot

  wxwidgets-sdk:
    source: https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.8.1/wxWidgets-3.2.8.1.tar.bz2
    source-checksum: sha256/ad0cf6c18815dcf1a6a89ad3c3d21a306cd7b5d99a602f77372ef1d92cb7d756
    plugin: autotools
    autotools-configure-parameters:
      - --enable-shared
      - --disable-aui
      - --disable-html
      - --disable-mdi
      - --disable-mediactrl
      - --disable-propgrid
      - --disable-ribbon
      - --disable-richtext
      - --disable-webview
      - --disable-xrc
      - --enable-unicode
      - --with-gtk=3
      - --without-opengl
      - --without-libnotify
      - --with-libjpeg
      - --with-libpng
      - --with-zlib
      - --prefix=/usr
    organize:
      snap/qalculate/current/usr: usr
    build-packages:
      - gcc
      - g++
      - gettext
      - libcairo2-dev
      - libexpat1-dev
      - libgtk-3-dev
      - libjpeg-dev
      - libpng-dev
      - libsecret-1-dev
      - libtiff5-dev
      - libxtst-dev
      - zlib1g-dev
    override-build: |
      set \
        -o errexit \
        -o nounset;
      craftctl default;
      # Fix-up wx-config link
      ln \
        --force \
        --relative \
        --symbolic \
        "${CRAFT_PART_INSTALL}"/usr/lib/wx/config/* \
        "${CRAFT_PART_INSTALL}"/usr/bin/wx-config;
      # Fix-up installation prefix
      # command line - How to use sed to replace only the first occurrence in a file? - Stack Overflow
      # https://stackoverflow.com/questions/148451/how-to-use-sed-to-replace-only-the-first-occurrence-in-a-file
      sed \
        --follow-symlinks \
        --in-place \
        "0,/^prefix=.*\$/ s##prefix=\"${SNAPCRAFT_STAGE}\"/usr#" \
        "${CRAFT_PART_INSTALL}"/usr/bin/wx-config;
    prime:
      - usr/lib/libwx_baseu-*
      - usr/lib/libwx-baseu_xml*
      - usr/lib/libwx_gtk3u_core*
      - usr/lib/libwx_gtk3u_adv*

  patches:
    source: snap/patches
    plugin: dump
    organize:
      "*": patches/
    prime:
      - -*
