name: qalculate-qt
confinement: strict
grade: stable
base: core24
compression: lzo
adopt-info: qalculate-qt
title: Qalculate! (Qt)
version: 5.8.1
license: GPL-2.0+
summary: The ultimate desktop calculator
description: |
  Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple
  to use but provides power and versatility normally reserved for complicated
  math packages, as well as useful tools for everyday needs (such as currency
  conversion and percent calculation). Features include a large library of
  customizable functions, unit calculations and conversion, physical constants,
  symbolic calculations (including integrals and equations), arbitrary precision,
  uncertainty propagation, interval arithmetic, plotting, and a user-friendly
  interface.

apps:
  qalculate-qt:
    extensions:
      - kde-neon-6
    common-id: io.github.Qalculate.qalculate-qt
    desktop: usr/share/applications/io.github.Qalculate.qalculate-qt.desktop
    command: usr/bin/qalculate-qt
    environment:
        GNUPLOT_DRIVER_DIR: "$SNAP/usr/libexec/gnuplot/6.0"
    plugs:
      - home
      - browser-support
  qalc:
    extensions:
      - kde-neon-6
    command: usr/bin/qalc
    environment:
        GNUPLOT_DRIVER_DIR: "$SNAP/usr/libexec/gnuplot/6.0"
  gnuplot:
    extensions:
      - kde-neon-6
    command: usr/bin/gnuplot
    environment:
        GNUPLOT_DRIVER_DIR: "$SNAP/usr/libexec/gnuplot/6.0"

slots:
  session-dbus-interface:
    interface: dbus
    name: io.github.Qalculate.qalculate-qt
    bus: session
parts:
  libqalculate:
    source: https://github.com/Qalculate/libqalculate.git
    source-tag: v5.8.1
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
    build-environment:
      - CXXFLAGS: -O2 -fsigned-char
    build-packages:
      - libncurses5-dev
      - libreadline-dev
      - libcurl4-gnutls-dev
      - libicu-dev
      - libxml2-dev
      - libgmp-dev
      - libmpfr-dev
      - intltool
      - doxygen
      - pkg-config
    stage-packages:
      - libmpfr6
      - libgmp10
    override-build: |
      cat $SNAPCRAFT_PROJECT_DIR/patches/snap-path.patch | patch -p1
      ./autogen.sh
      craftctl default
      echo Stripping qalc
      strip $CRAFT_PART_INSTALL/usr/bin/qalc
    after:
      - patches
    prime:
      - -include
      - -lib/pkgconfig
      - -lib/*.a
      - -share/doc
      - -usr/share/doc
      - -usr/share/lintian

  qalculate-qt:
    source: https://github.com/Qalculate/qalculate-qt/releases/download/v5.8.1/qalculate-qt-5.8.1.tar.gz
    source-checksum: sha512/1609b71051895f202dd91ca031d763bfdb2f8708b52e54797c05d88c8c7d87a90ab6ba872436e51129c207dd05d27e61869819c4c655c7706c91cee63e792ab5
    plugin: qmake
    qmake-parameters:
      - COMPILES_RESOURCES=yes PREFIX=/usr
    build-environment:
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:/snap/kf6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr
      - PKG_CONFIG_PATH: $CRAFT_STAGE//usr/lib/pkgconfig:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
      - PATH: /snap/kde-qt6-core24-sdk/current/usr/bin/qt6:$PATH
    build-snaps:
      - core24
      - kf6-core24
    build-packages:
      - libgmp-dev
      - libxml2-dev
    after:
      - libqalculate
      - patches
    prime:
      - -share/applications
    override-pull: |
      craftctl default
      cat $SNAPCRAFT_PROJECT_DIR/patches/snap.patch | patch -p1
      cat $SNAPCRAFT_PROJECT_DIR/patches/snap-icon.patch | patch -p1

  gnuplot:
    source: https://downloads.sourceforge.net/gnuplot/gnuplot-6.0.3.tar.gz
    source-checksum: sha256/ec52e3af8c4083d4538152b3f13db47f6d29929a3f6ecec5365c834e77f251ab
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --without-gd
      - --without-libcerf
      - --without-lua
      - --with-readline=gnu
      - --without-qt
    prime:
      - -share/applications
      - -share/doc
      - -share/man
    override-build: |
      craftctl default
      echo Stripping gnuplot
      strip $CRAFT_PART_INSTALL/usr/bin/gnuplot

  patches:
    source: snap/patches
    plugin: dump
    organize:
      "*": patches/
    prime:
      - -*
