name: qalculate-qt
adopt-info: qalculate-qt
title: Qalculate! (Qt)
version: 5.8.1
license: GPL-2.0+
summary: The ultimate desktop calculator
description: |
  Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple
  to use but provides power and versatility normally reserved for complicated
  math packages, as well as useful tools for everyday needs (such as currency
  conversion and percent calculation). Features include a large library of
  customizable functions, unit calculations and conversion, physical constants,
  symbolic calculations (including integrals and equations), arbitrary precision,
  uncertainty propagation, interval arithmetic, plotting, and a user-friendly
  interface.

confinement: strict
grade: stable
base: core24
compression: lzo

platforms:
  amd64:
  arm64:

apps:
  qalculate-qt:
    extensions:
      - kde-neon-6
    common-id: io.github.Qalculate.qalculate-qt
    desktop: usr/share/applications/io.github.Qalculate.qalculate-qt.desktop
    command: usr/bin/qalculate-qt
    environment:
        GNUPLOT_DRIVER_DIR: "$SNAP/usr/libexec/gnuplot/6.0"
    plugs:
      - home
      - browser-support
  qalc:
    extensions:
      - kde-neon-6
    command: usr/bin/qalc
    environment:
        GNUPLOT_DRIVER_DIR: "$SNAP/usr/libexec/gnuplot/6.0"
  gnuplot:
    extensions:
      - kde-neon-6
    command: usr/bin/gnuplot
    environment:
        GNUPLOT_DRIVER_DIR: "$SNAP/usr/libexec/gnuplot/6.0"

slots:
  session-dbus-interface:
    interface: dbus
    name: io.github.Qalculate.qalculate-qt
    bus: session
parts:
  libqalculate:
    source: https://github.com/Qalculate/libqalculate.git
    source-tag: v5.8.1
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
    build-environment:
      - CXXFLAGS: -O2 -fsigned-char
    build-packages:
      - libncurses5-dev
      - libreadline-dev
      - libcurl4-gnutls-dev
      - libicu-dev
      - libxml2-dev
      - libgmp-dev
      - libmpfr-dev
      - intltool
      - doxygen
      - pkg-config
    stage-packages:
      - libmpfr6
      - libgmp10
    override-build: |
      patch -p1 < $CRAFT_STAGE/patches/snap-path.patch
      ./autogen.sh
      craftctl default
      echo Stripping qalc
      strip $CRAFT_PART_INSTALL/usr/bin/qalc
    after:
      - patches
    prime:
      - -include
      - -lib/pkgconfig
      - -lib/*.a
      - -share/doc
      - -usr/share/doc
      - -usr/share/lintian

  qalculate-qt:
    source: https://github.com/Qalculate/qalculate-qt/releases/download/v5.8.1/qalculate-qt-5.8.1.tar.gz
    source-checksum: sha512/1609b71051895f202dd91ca031d763bfdb2f8708b52e54797c05d88c8c7d87a90ab6ba872436e51129c207dd05d27e61869819c4c655c7706c91cee63e792ab5
    plugin: qmake
    qmake-parameters:
      - COMPILES_RESOURCES=yes PREFIX=/usr
    build-environment:
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:/snap/kf6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr
      - PKG_CONFIG_PATH: $CRAFT_STAGE//usr/lib/pkgconfig:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
      - PATH: /snap/kde-qt6-core24-sdk/current/usr/bin/qt6:$PATH
    build-snaps:
      - core24
      - kf6-core24
    build-packages:
      - libgmp-dev
      - libxml2-dev
    after:
      - libqalculate
      - patches
    prime:
      - -share/applications
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/snap/patches/snap.patch
      patch -p1 < $CRAFT_PROJECT_DIR/snap/patches/snap-icon.patch

  gnuplot:
    source: https://downloads.sourceforge.net/gnuplot/gnuplot-6.0.3.tar.gz
    source-checksum: sha256/ec52e3af8c4083d4538152b3f13db47f6d29929a3f6ecec5365c834e77f251ab
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --without-gd
      - --without-libcerf
      - --without-lua
      - --with-readline=gnu
      - --without-qt
      - --enable-wxwidgets
    after:
      - wxwidgets-sdk
    prime:
      - -share/applications
      - -share/doc
      - -share/man
    override-build: |
      craftctl default
      echo Stripping gnuplot
      strip $CRAFT_PART_INSTALL/usr/bin/gnuplot

  wxwidgets-sdk:
    source: https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.8.1/wxWidgets-3.2.8.1.tar.bz2
    source-checksum: sha256/ad0cf6c18815dcf1a6a89ad3c3d21a306cd7b5d99a602f77372ef1d92cb7d756
    plugin: autotools
    autotools-configure-parameters:
      - --enable-shared
      - --disable-aui
      - --disable-html
      - --disable-mdi
      - --disable-mediactrl
      - --disable-propgrid
      - --disable-ribbon
      - --disable-richtext
      - --disable-webview
      - --disable-xrc
      - --enable-unicode
      - --with-gtk=3
      - --without-opengl
      - --without-libnotify
      - --with-libjpeg
      - --with-libpng
      - --with-zlib
      - --prefix=/usr
    organize:
      snap/qalculate/current/usr: usr
    build-packages:
      - gcc
      - g++
      - gettext
      - libcairo2-dev
      - libexpat1-dev
      - libgtk-3-dev
      - libjpeg-dev
      - libpng-dev
      - libsecret-1-dev
      - libtiff5-dev
      - libxtst-dev
      - zlib1g-dev
    override-build: |
      set \
        -o errexit \
        -o nounset;
      craftctl default;
      # Fix-up wx-config link
      ln \
        --force \
        --relative \
        --symbolic \
        "${CRAFT_PART_INSTALL}"/usr/lib/wx/config/* \
        "${CRAFT_PART_INSTALL}"/usr/bin/wx-config;
      # Fix-up installation prefix
      # command line - How to use sed to replace only the first occurrence in a file? - Stack Overflow
      # https://stackoverflow.com/questions/148451/how-to-use-sed-to-replace-only-the-first-occurrence-in-a-file
      sed \
        --follow-symlinks \
        --in-place \
        "0,/^prefix=.*\$/ s##prefix=\"${SNAPCRAFT_STAGE}\"/usr#" \
        "${CRAFT_PART_INSTALL}"/usr/bin/wx-config;
    prime:
      - usr/lib/libwx_baseu-*
      - usr/lib/libwx-baseu_xml*
      - usr/lib/libwx_gtk3u_core*
      - usr/lib/libwx_gtk3u_adv*

  patches:
    source: snap/patches
    plugin: dump
    organize:
      "*": patches/
    prime:
      - -*
